/* OMACHESS board colours, generated by Omarchy from the active theme.
 *
 * Install:
 *     cp themes/omachess.css.tpl ~/.config/omarchy/themed/
 *     omarchy-theme-set <your theme>     # or switch themes once
 *
 * Omarchy renders every template in ~/.config/omarchy/themed into the active
 * theme directory, so this becomes
 *     ~/.local/state/omarchy/current/theme/omachess.css
 * which OMACHESS loads on top of its built-in stylesheet.
 *
 * This file is OPTIONAL and changes the board's appearance.
 *
 * By default the board is wood, deliberately ignoring the theme: square colour
 * is a property of a chess board, not of a desktop palette. Installing this
 * template replaces that wood with your theme's colours instead. Everything
 * around the board already follows the theme with or without this file.
 *
 * Piece colours are deliberately absent: a white piece must read as white in
 * every theme, so the binary fixes those.
 */

.omachess-board {
    background-color: {{ background }};
}

.omachess-square.light {
    background-color: {{ selection }};
}

.omachess-square.dark {
    background-color: {{ lighter_background }};
}

.omachess-square.selected {
    box-shadow: inset 0 0 0 3px {{ accent }};
}

.omachess-board.wrong .omachess-square.light {
    background-color: {{ red }};
}

.omachess-board.wrong .omachess-square.dark {
    background-color: {{ red }};
}
